python seg/train.py \
--source ../data/images \
--model wodis \
--model_name train_wodis \
--workers 2 \
--validation \
--batch_size 4 \
--epochs 100 \
--separation_loss csol \
--separation_loss_lambda 0.01 \
--output_dir seg/output \
--datetime `date +%Y%m%d%H%M%S`